description: 'Allocation de présence parentale (APP) : montants'
montant_taux_plein_bmaf:
  description: Montant taux plein (% BMAF)
  seul:
    description: Seul
    values:
      '2006-06-04':
        value: null
      '2002-04-01':
        value: 2.7789
      '2001-01-01':
        value: 1.8854
    metadata:
      unit: /1
  metadata:
    order:
    - seul
metadata:
  order:
  - montant_taux_plein_bmaf
  - montant_taux_partiel_bmaf
  - duree_maximale_allocation_annee
  reference:
    '2006-06-04': Décret 2006-659 du 02/06/2006
    '2002-04-01': Décret 2002-373 du 19/03/2002, art. 1
    '2001-01-01': Décret 2001-106 du 05/02/2001, art. 2
  date_parution_jo:
    '2006-06-04': '2006-06-04'
    '2002-04-01': '2002-03-21'
    '2001-01-01': '2001-02-07'
  notes:
    '2006-06-04': APP devient AJPP
    '2001-01-01': Création de l'Allocation de Présence Parentale
montant_taux_partiel_bmaf:
  description: Montant taux partiel (% BMAF)
  50_duree_legale_seul:
    description: 50% durée légale, Seul
    values:
      '2006-06-04':
        value: null
      '2002-04-01':
        value: 1.4626
      '2001-01-01':
        value: 1.2444
    metadata:
      unit: /1
  metadata:
    order:
    - 50_duree_legale_seul
duree_maximale_allocation_annee:
  description: Durée maximale de l'allocation (année)
  values:
    '2006-06-04':
      value: null
    '2001-01-01':
      value: 1.0
documentation: ''
