description: 'Allocation de présence parentale (APP) : montants'
duree_maximale_allocation_annee:
  description: Durée maximale de l'allocation (année)
  values:
    '2001-01-01':
      value: 1.0
    '2006-06-04':
      value: null
metadata:
  order:
  - montant_taux_plein_bmaf
  - montant_taux_partiel_bmaf
  - duree_maximale_allocation_annee
montant_taux_partiel_bmaf:
  50_duree_legale_couple:
    description: 50% durée légale, Couple
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 0.9427
      '2002-04-01':
        value: 1.1701
      '2006-06-04':
        value: null
  50_duree_legale_seul:
    description: 50% durée légale, Seul
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 1.2444
      '2002-04-01':
        value: 1.4626
      '2006-06-04':
        value: null
  80_duree_legale_couple:
    description: 80% durée légale, Couple
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 0.7129
      '2006-06-04':
        value: null
  80_duree_legale_seul:
    description: 80% durée légale, Seul
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 0.9427
      '2006-06-04':
        value: null
  description: Montant taux partiel (% BMAF)
  metadata:
    order:
    - 80_duree_legale_couple
    - 80_duree_legale_seul
    - 50_duree_legale_couple
    - 50_duree_legale_seul
montant_taux_plein_bmaf:
  couple:
    description: Couple
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 1.4257
      '2002-04-01':
        value: 2.3401
      '2006-06-04':
        value: null
  description: Montant taux plein (% BMAF)
  metadata:
    order:
    - couple
    - seul
  seul:
    description: Seul
    metadata:
      unit: /1
    values:
      '2001-01-01':
        value: 1.8854
      '2002-04-01':
        value: 2.7789
      '2006-06-04':
        value: null
