autres_huiles_legeres_hectolitre:
  description: Autres huiles légères (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 311.25
    '1994-01-01':
      value: 347.41
    '1995-01-01':
      value: 367.92
    '1996-01-01':
      value: 380.92
    '1997-01-01':
      value: 386.92
    '1998-01-01':
      value: 394.92
    '1999-01-01':
      value: 398.86
    '2000-01-01':
      value: 384.62
    '2002-01-01':
      value: 58.63
    '2003-01-01':
      value: 58.92
    '2006-01-01':
      value: 60.69
    '2008-01-01':
      value: 58.92
    '2015-01-01':
      value: 60.64
    '2016-01-01':
      value: 62.35
    '2017-01-01':
      value: 64.3
    '2018-01-01':
      value: 67.52
    '2019-01-01':
      value: 69.9
    '2020-01-01':
      value: 72.28
    '2021-01-01':
      value: 74.66
    '2022-01-01':
      value: 77.03
autres_huiles_moyennes_hectolitre:
  description: Autres huiles moyennes (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 255.18
    '2002-01-01':
      value: 38.9
    '2003-01-01':
      value: 39.19
    '2004-01-01':
      value: 41.69
    '2006-01-01':
      value: 42.84
    '2008-01-01':
      value: 41.69
    '2015-01-01':
      value: 43.6
    '2016-01-01':
      value: 45.51
    '2017-01-01':
      value: 47.68
    '2018-01-01':
      value: 51.28
    '2019-01-01':
      value: 53.93
    '2020-01-01':
      value: 56.58
    '2021-01-01':
      value: 59.24
    '2022-01-01':
      value: 61.89
carburateurs_type_essence_autres_hectolitre:
  description: Carburateurs type essence, autres (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-01-01':
      value: 58.92
    '2015-01-01':
      value: 60.83
    '2016-01-01':
      value: 62.74
    '2017-01-01':
      value: 64.91
    '2018-01-01':
      value: 68.51
    '2019-01-01':
      value: 71.16
    '2020-01-01':
      value: 73.81
    '2021-01-01':
      value: 76.47
    '2022-01-01':
      value: 79.12
carburateurs_type_essence_carburants_avion_hectolitre:
  description: Carburateurs type essence, carburants pour avion (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 311.25
    '1994-01-01':
      value: 347.41
    '1995-01-01':
      value: 367.92
    '1996-01-01':
      value: 380.92
    '1997-01-01':
      value: 386.92
    '1998-01-01':
      value: 394.92
    '1999-01-01':
      value: 398.86
    '2000-01-01':
      value: 384.62
    '2002-01-01':
      value: 58.63
    '2003-01-01':
      value: 58.92
    '2006-01-01':
      value: 60.69
    '2008-01-01':
      value: 30.2
    '2015-01-01':
      value: 32.11
    '2016-01-01':
      value: 34.02
    '2017-01-01':
      value: 36.19
    '2018-01-01':
      value: 39.79
    '2019-01-01':
      value: 42.44
    '2020-01-01':
      value: 45.09
    '2021-01-01':
      value: 47.75
    '2022-01-01':
      value: 50.4
carburateurs_type_essence_sous_conditions_hectolitre:
  description: Carburateurs type essence, sous conditions (hectolitre)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: 11.97
    '1993-04-15':
      value: 12.22
    '1994-01-01':
      value: 13.58
    '1995-01-01':
      value: 13.81
    '1996-01-01':
      value: 14.07
    '1997-01-01':
      value: 14.37
    '1998-01-01':
      value: 14.56
    '1999-01-01':
      value: 14.69
    '2000-01-01':
      value: 14.76
    '2002-01-01':
      value: 2.25
    '2003-01-01':
      value: 2.54
    '2014-04-01':
      value: null
carbureacteurs_type_petrole_lampant_autres_hectolitre:
  description: Carburéacteurs, type pétrole lampant, autres (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-01-01':
      value: 41.69
    '2015-01-01':
      value: 43.6
    '2016-01-01':
      value: 45.51
    '2017-01-01':
      value: 47.68
    '2018-01-01':
      value: 51.28
    '2019-01-01':
      value: 53.93
    '2020-01-01':
      value: 56.58
    '2021-01-01':
      value: 59.24
    '2022-01-01':
      value: 61.89
carbureacteurs_type_petrole_lampant_carburant_moteurs_avion_hectolitre:
  description: Carburéacteurs, type pétrole lampant, carburant moteurs d'avion (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 255.18
    '2002-01-01':
      value: 38.9
    '2003-01-01':
      value: 39.19
    '2004-01-01':
      value: 41.69
    '2006-01-01':
      value: 42.84
    '2008-01-01':
      value: 30.2
    '2015-01-01':
      value: 32.11
    '2016-01-01':
      value: 34.02
    '2017-01-01':
      value: 36.19
    '2018-01-01':
      value: 39.79
    '2019-01-01':
      value: 42.44
    '2020-01-01':
      value: 45.09
    '2021-01-01':
      value: 47.75
    '2022-01-01':
      value: 50.4
carbureacteurs_type_petrole_lampant_sous_conditions_hectolitre:
  description: Carburéacteurs, type pétrole lampant , sous conditions (hectolitre)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: 11.97
    '1993-04-15':
      value: 12.22
    '1994-01-01':
      value: 13.58
    '1995-01-01':
      value: 13.81
    '1996-01-01':
      value: 14.07
    '1997-01-01':
      value: 14.37
    '1998-01-01':
      value: 14.56
    '1999-01-01':
      value: 14.69
    '2000-01-01':
      value: 14.76
    '2002-01-01':
      value: 2.25
    '2003-01-01':
      value: 2.54
    '2014-04-01':
      value: null
description: TICPE - produits énergétiques b
gazole_comme_carburants_sous_conditions_hectolitre:
  description: Gazole comme carburants sous conditions (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 42.85
    '1994-01-01':
      value: 47.59
    '1995-01-01':
      value: 48.4
    '1996-01-01':
      value: 49.32
    '1997-01-01':
      value: 50.36
    '1998-01-01':
      value: 51.01
    '1999-01-01':
      value: 51.47
    '2000-01-01':
      value: 51.73
    '2002-01-01':
      value: 5.49
    '2003-01-01':
      value: 5.66
    '2012-01-01':
      value: 7.2
    '2014-04-01':
      value: 8.86
    '2015-01-01':
      value: 10.84
    '2016-01-01':
      value: 12.83
    '2017-01-01':
      value: 15.09
    '2018-01-01':
      value: 18.82
    '2019-01-01':
      value: 21.58
    '2020-01-01':
      value: 24.34
    '2021-01-01':
      value: 27.09
    '2022-01-01':
      value: 29.85
gazole_fioul_domestique_hectolitre:
  description: Gazole, fioul domestique (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-01-01':
      value: 5.66
    '2015-01-01':
      value: 7.64
    '2016-01-01':
      value: 9.63
    '2017-01-01':
      value: 11.89
    '2018-01-01':
      value: 15.62
    '2019-01-01':
      value: 18.38
    '2020-01-01':
      value: 21.14
    '2021-01-01':
      value: 23.89
    '2022-01-01':
      value: 26.65
metadata:
  order:
  - carburateurs_type_essence_sous_conditions_hectolitre
  - carburateurs_type_essence_carburants_avion_hectolitre
  - carburateurs_type_essence_autres_hectolitre
  - autres_huiles_legeres_hectolitre
  - petrole_lampant_utilise_comme_combustible_hectolitre
  - petrole_lampant_autre_hectolitre
  - carbureacteurs_type_petrole_lampant_sous_conditions_hectolitre
  - carbureacteurs_type_petrole_lampant_carburant_moteurs_avion_hectolitre
  - carbureacteurs_type_petrole_lampant_autres_hectolitre
  - autres_huiles_moyennes_hectolitre
  - gazole_comme_carburants_sous_conditions_hectolitre
  - gazole_fioul_domestique_hectolitre
petrole_lampant_autre_hectolitre:
  description: Pétrole lampant, autre (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 255.18
    '2002-01-01':
      value: 38.9
    '2003-01-01':
      value: 39.19
    '2004-01-01':
      value: 41.69
    '2006-01-01':
      value: 42.84
    '2008-01-01':
      value: 41.69
    '2015-01-01':
      value: 43.6
    '2016-01-01':
      value: 45.51
    '2017-01-01':
      value: 47.68
    '2018-01-01':
      value: 51.28
    '2019-01-01':
      value: 53.93
    '2020-01-01':
      value: 56.58
    '2021-01-01':
      value: 59.24
    '2022-01-01':
      value: 61.89
petrole_lampant_utilise_comme_combustible_hectolitre:
  description: Pétrole lampant utilisé comme combustible (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 51.73
    '2002-01-01':
      value: 5.49
    '2003-01-01':
      value: 5.66
    '2015-01-01':
      value: 7.57
    '2016-01-01':
      value: 9.48
    '2017-01-01':
      value: 11.65
    '2018-01-01':
      value: 15.25
    '2019-01-01':
      value: 17.9
    '2020-01-01':
      value: 20.55
    '2021-01-01':
      value: 23.21
    '2022-01-01':
      value: 25.86
