autres_gaz_petrole_liquefies_utilises_comme_carburants_autres_100kg:
  description: Autres gaz de pétrole liquéfiés utilisés comme carburants, autres (100kg)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: 216.0
    '1993-04-15':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: 217.49
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: 241.56
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: 245.67
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: 74.34
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: 75.9
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: 70.0
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: 65.71
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: 65.71
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: 10.02
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: 10.76
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: 10.76
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: 10.76
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 10.76
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 10.76
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 10.76
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 10.76
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 10.76
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 10.76
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 10.76
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 10.76
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 13.0
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 13.97
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 16.5
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 20.71
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 23.82
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 26.92
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 30.03
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 33.13
autres_gaz_petrole_liquefies_utilises_comme_carburants_sous_conditions_100kg:
  description: Autres gaz de pétrole liquéfiés utilisés comme carburants, sous conditions
    (100kg)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: 53.43
    '1993-04-15':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: 54.55
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: 24.12
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: 24.53
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: 25.0
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: 25.53
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: 25.86
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: 25.86
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: 25.86
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: 3.94
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: 4.68
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: 4.68
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: 4.68
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 4.68
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 4.68
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 4.68
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 4.68
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 4.68
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 4.68
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 4.68
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 4.68
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 6.92
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 9.16
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 11.69
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 15.9
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 19.01
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 22.11
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 25.22
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 28.32
description: TICPE - produits énergétiques d
gaz_naturel_etat_gazeux_utilise_sous_conditions_aux_moteurs_stationnaires_100m3:
  description: Gaz naturel à l'état gazeux, utilisé sous conditions aux moteurs stationnaires
    (100m3)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: null
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: null
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: null
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: null
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: null
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 0.0
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 0.0
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 0.0
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 0.0
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 0.0
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 0.0
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 0.0
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 1.49
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 3.09
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 4.69
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 6.5
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 9.5
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 11.72
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 13.92
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 16.15
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 18.36
gaz_naturel_etat_gazeux_utilises_comme_carburants_100m3:
  description: Gaz naturel à l'état gazeux, utilisés comme carburants (100m3)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1993-04-15':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: 55.446
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: 61.59
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: 62.64
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: 63.83
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: 65.17
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: 60.0
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: 55.0
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: 55.0
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: 8.38
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: 8.47
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: 8.47
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: 8.47
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 0.0
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 0.0
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 0.0
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 0.0
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 0.0
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 0.0
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 0.0
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 1.49
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 3.09
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 3.99
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 5.8
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 5.8
metadata:
  rank: 3
