description: TICPE - produits énergétiques a
essence_normale_hectolitre:
  description: Essence normale (hectolitre)
  metadata:
    unit: currency-FRF
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 311.25
    '1994-01-01':
      value: 347.41
    '1995-01-01':
      value: 367.92
    '1996-01-01':
      value: 380.92
    '1997-01-01':
      value: 386.92
    '1998-01-01':
      value: 394.92
    '1999-01-01':
      value: 398.86
    '2000-01-01':
      value: null
essences_speciales_utilisees_comme_carburants_combustibles_hectolitre:
  description: Essences spéciales utilisées comme carburants et combustibles (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 311.25
    '1994-01-01':
      value: 347.41
    '1995-01-01':
      value: 367.92
    '1996-01-01':
      value: 380.92
    '1997-01-01':
      value: 386.92
    '1998-01-01':
      value: 394.92
    '1999-01-01':
      value: 398.86
    '2000-01-01':
      value: 384.62
    '2002-01-01':
      value: 58.63
    '2003-01-01':
      value: 58.92
    '2006-01-01':
      value: 60.69
    '2008-01-01':
      value: 58.92
    '2015-01-01':
      value: 60.64
    '2016-01-01':
      value: 62.35
    '2017-01-01':
      value: 64.3
    '2018-01-01':
      value: 67.52
    '2019-01-01':
      value: 69.9
    '2020-01-01':
      value: 72.28
    '2021-01-01':
      value: 74.66
    '2022-01-01':
      value: 77.03
goudrons_utilises_comme_combustibles_100kg:
  description: Goudrons utilisés comme combustibles, (100kg)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 6.65
    '1994-01-01':
      value: 7.39
    '1995-01-01':
      value: 7.52
    '1996-01-01':
      value: 7.66
    '1997-01-01':
      value: 7.82
    '1998-01-01':
      value: 7.92
    '1999-01-01':
      value: 7.99
    '2000-01-01':
      value: 8.03
    '2002-01-01':
      value: 1.22
    '2008-01-01':
      value: 1.5
    '2014-04-01':
      value: 1.58
    '2015-01-01':
      value: 3.28
    '2016-01-01':
      value: 4.97
    '2017-01-01':
      value: 6.89
    '2018-01-01':
      value: 10.08
    '2019-01-01':
      value: 12.43
    '2020-01-01':
      value: 14.78
    '2021-01-01':
      value: 17.13
    '2022-01-01':
      value: 19.48
huiles_legeres_preparation_essence_aviation_hectolitre:
  description: Huiles légères et préparation, essence d'aviation (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 175.82
    '1994-01-01':
      value: 195.28
    '1995-01-01':
      value: 198.6
    '1996-01-01':
      value: 202.37
    '1997-01-01':
      value: 206.82
    '1998-01-01':
      value: 209.31
    '1999-01-01':
      value: 211.19
    '2000-01-01':
      value: 212.25
    '2002-01-01':
      value: 32.36
    '2008-01-01':
      value: 35.9
    '2015-01-01':
      value: 37.81
    '2016-01-01':
      value: 39.72
    '2017-01-01':
      value: 41.89
    '2018-01-01':
      value: 45.49
    '2019-01-01':
      value: 48.14
    '2020-01-01':
      value: 50.79
    '2021-01-01':
      value: 53.45
    '2022-01-01':
      value: 56.1
metadata:
  order:
  - goudrons_utilises_comme_combustibles_100kg
  - white_spirit_utilise_comme_combustible_hectolitre
  - essences_speciales_utilisees_comme_carburants_combustibles_hectolitre
  - huiles_legeres_preparation_essence_aviation_hectolitre
  - supercarburants_dont_sp95_sp98_hectolitre
  - supercarburants_contenant_additif_hectolitre
  - supere10_hectolitre
  - essence_normale_hectolitre
supercarburants_contenant_additif_hectolitre:
  description: Supercarburants contenant un additif (hectolitre)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 326.84
    '1994-01-01':
      value: 363.0
    '1995-01-01':
      value: 383.51
    '1996-01-01':
      value: 396.51
    '1997-01-01':
      value: 403.51
    '1998-01-01':
      value: 411.51
    '1999-01-01':
      value: 415.5
    '2000-01-01':
      value: 417.68
    '2002-01-01':
      value: 63.67
    '2003-01-01':
      value: 63.96
    '2015-01-01':
      value: 65.68
    '2016-01-01':
      value: 67.39
    '2017-01-01':
      value: 68.34
    '2018-01-01':
      value: 71.56
    '2019-01-01':
      value: 73.94
    '2020-01-01':
      value: 76.32
    '2021-01-01':
      value: 78.7
    '2022-01-01':
      value: 81.07
supercarburants_dont_sp95_sp98_hectolitre:
  description: Supercarburants dont SP95 et SP98 (hectolitre)*
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 290.12
    '1994-01-01':
      value: 329.5
    '1995-01-01':
      value: 357.23
    '1996-01-01':
      value: 370.23
    '1997-01-01':
      value: 376.23
    '1998-01-01':
      value: 384.23
    '1999-01-01':
      value: 384.62
    '2002-01-01':
      value: 58.63
    '2003-01-01':
      value: 58.92
    '2006-01-01':
      value: 60.69
    '2015-01-01':
      value: 62.41
    '2016-01-01':
      value: 64.12
    '2017-01-01':
      value: 65.07
    '2018-01-01':
      value: 68.29
    '2019-01-01':
      value: 70.67
    '2020-01-01':
      value: 73.05
    '2021-01-01':
      value: 75.43
    '2022-01-01':
      value: 65.07
supere10_hectolitre:
  description: SuperE10 (hectolitre) *
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-12-29':
      value: 60.69
    '2015-01-01':
      value: 62.41
    '2016-01-01':
      value: 62.12
    '2017-01-01':
      value: 63.07
    '2018-01-01':
      value: 66.29
    '2019-01-01':
      value: 68.7
    '2020-01-01':
      value: 71.05
    '2021-01-01':
      value: 73.43
    '2022-01-01':
      value: 75.8
white_spirit_utilise_comme_combustible_hectolitre:
  description: White Spirit utilisé comme combustible (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 51.73
    '2002-01-01':
      value: 5.49
    '2003-01-01':
      value: 5.66
    '2015-01-01':
      value: 7.87
    '2016-01-01':
      value: 10.08
    '2017-01-01':
      value: 12.02
    '2018-01-01':
      value: 15.25
    '2019-01-01':
      value: 17.64
    '2020-01-01':
      value: 20.02
    '2021-01-01':
      value: 22.4
    '2022-01-01':
      value: 24.78
