carburant_constitue_100_estars_methyliques_acides_gras_hectolitre:
  description: Carburant constitué à 100% d'estars méthyliques d'acides gras (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2018-01-01':
      value: 11.83
    '2019-01-01':
      value: 13.31
    '2020-01-01':
      value: 15.39
    '2021-01-01':
      value: 17.17
    '2022-01-01':
      value: 18.95
carburant_constitue_minimum_90_alcool_ethylique_agricole_hectolitre:
  description: Carburant constitué d'au minimum 90% d'alcool éthylique agricole (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2017-01-01':
      value: 4.4
    '2018-01-01':
      value: 6.43
    '2019-01-01':
      value: 7.93
    '2020-01-01':
      value: 9.43
    '2021-01-01':
      value: 10.93
    '2022-01-01':
      value: 12.43
description: TICPE - produits énergétiques e
emulsion_eau_dans_gazole_autres_hectolitre:
  description: Emulsion d'eau dans du gazole …, autres (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 198.95
    '2002-01-01':
      value: 24.54
    '2008-01-01':
      value: 30.2
    '2009-01-01':
      value: 26.27
    '2010-01-01':
      value: 24.78
    '2010-03-11':
      value: 28.71
    '2015-01-01':
      value: 30.35
    '2016-01-01':
      value: 32.0
    '2017-01-01':
      value: 33.86
    '2018-01-01':
      value: 36.94
    '2019-01-01':
      value: 39.22
    '2020-01-01':
      value: 41.5
    '2021-01-01':
      value: 43.77
    '2022-01-01':
      value: 46.05
emulsion_eau_dans_gazole_sous_conditions_hectolitre:
  description: Emulsion d'eau dans du gazole …, sous conditions (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 40.85
    '2002-01-01':
      value: 1.8
    '2008-01-01':
      value: 2.1
    '2015-01-01':
      value: 3.74
    '2016-01-01':
      value: 5.39
    '2017-01-01':
      value: 7.25
    '2018-01-01':
      value: 10.33
    '2019-01-01':
      value: 12.61
    '2020-01-01':
      value: 14.89
    '2021-01-01':
      value: 17.16
    '2022-01-01':
      value: 19.44
metadata:
  order:
  - emulsion_eau_dans_gazole_sous_conditions_hectolitre
  - emulsion_eau_dans_gazole_autres_hectolitre
  - super_e_85_utilise_comme_carburant_hectolitre
  - carburant_constitue_minimum_90_alcool_ethylique_agricole_hectolitre
  - carburant_constitue_100_estars_methyliques_acides_gras_hectolitre
super_e_85_utilise_comme_carburant_hectolitre:
  description: Super E 85 utilisé comme carburant (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-01-01':
      value: 28.33
    '2009-01-01':
      value: 23.24
    '2010-01-01':
      value: 20.69
    '2011-01-01':
      value: 17.29
    '2014-04-01':
      value: 12.4
    '2015-01-01':
      value: 12.62
    '2016-01-01':
      value: 7.96
    '2017-01-01':
      value: 9.41
    '2018-01-01':
      value: 11.83
    '2019-01-01':
      value: 13.61
    '2020-01-01':
      value: 15.39
    '2021-01-01':
      value: 17.17
    '2022-01-01':
      value: 18.95
