autres_gaz_petrole_liquefies_utilises_comme_carburants_autres_100kg:
  description: Autres gaz de pétrole liquéfiés utilisés comme carburants, autres (100kg)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: 216.0
    '1993-04-15':
      value: 217.49
    '1994-01-01':
      value: 241.56
    '1995-01-01':
      value: 245.67
    '1996-01-01':
      value: 74.34
    '1997-01-01':
      value: 75.9
    '1998-01-01':
      value: 70.0
    '1999-01-01':
      value: 65.71
    '2002-01-01':
      value: 10.02
    '2003-01-01':
      value: 10.76
    '2015-01-01':
      value: 13.0
    '2016-01-01':
      value: 13.97
    '2017-01-01':
      value: 16.5
    '2018-01-01':
      value: 20.71
    '2019-01-01':
      value: 23.82
    '2020-01-01':
      value: 26.92
    '2021-01-01':
      value: 30.03
    '2022-01-01':
      value: 33.13
autres_gaz_petrole_liquefies_utilises_comme_carburants_sous_conditions_100kg:
  description: Autres gaz de pétrole liquéfiés utilisés comme carburants, sous conditions
    (100kg)
  metadata:
    unit:
      '1993-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: 53.43
    '1993-04-15':
      value: 54.55
    '1994-01-01':
      value: 24.12
    '1995-01-01':
      value: 24.53
    '1996-01-01':
      value: 25.0
    '1997-01-01':
      value: 25.53
    '1998-01-01':
      value: 25.86
    '2002-01-01':
      value: 3.94
    '2003-01-01':
      value: 4.68
    '2015-01-01':
      value: 6.92
    '2016-01-01':
      value: 9.16
    '2017-01-01':
      value: 11.69
    '2018-01-01':
      value: 15.9
    '2019-01-01':
      value: 19.01
    '2020-01-01':
      value: 22.11
    '2021-01-01':
      value: 25.22
    '2022-01-01':
      value: 28.32
description: TICPE - produits énergétiques d
gaz_naturel_etat_gazeux_utilise_sous_conditions_aux_moteurs_stationnaires_100m3:
  description: Gaz naturel à l'état gazeux, utilisé sous conditions aux moteurs stationnaires
    (100m3)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2008-01-01':
      value: 0.0
    '2014-04-01':
      value: 1.49
    '2015-01-01':
      value: 3.09
    '2016-01-01':
      value: 4.69
    '2017-01-01':
      value: 6.5
    '2018-01-01':
      value: 9.5
    '2019-01-01':
      value: 11.72
    '2020-01-01':
      value: 13.92
    '2021-01-01':
      value: 16.15
    '2022-01-01':
      value: 18.36
gaz_naturel_etat_gazeux_utilises_comme_carburants_100m3:
  description: Gaz naturel à l'état gazeux, utilisés comme carburants (100m3)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 55.446
    '1994-01-01':
      value: 61.59
    '1995-01-01':
      value: 62.64
    '1996-01-01':
      value: 63.83
    '1997-01-01':
      value: 65.17
    '1998-01-01':
      value: 60.0
    '1999-01-01':
      value: 55.0
    '2002-01-01':
      value: 8.38
    '2003-01-01':
      value: 8.47
    '2008-01-01':
      value: 0.0
    '2014-04-01':
      value: 1.49
    '2015-01-01':
      value: 3.09
    '2016-01-01':
      value: 3.99
    '2017-01-01':
      value: 5.8
metadata:
  order:
  - autres_gaz_petrole_liquefies_utilises_comme_carburants_sous_conditions_100kg
  - autres_gaz_petrole_liquefies_utilises_comme_carburants_autres_100kg
  - gaz_naturel_etat_gazeux_utilises_comme_carburants_100m3
  - gaz_naturel_etat_gazeux_utilise_sous_conditions_aux_moteurs_stationnaires_100m3
