carburant_constitue_100_estars_methyliques_acides_gras_hectolitre:
  description: Carburant constitué à 100% d'estars méthyliques d'acides gras (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: null
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: null
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: null
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: null
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: null
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: null
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: null
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: null
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: null
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: null
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: null
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: null
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: null
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: null
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: null
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: null
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 11.83
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 13.31
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 15.39
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 17.17
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 18.95
carburant_constitue_minimum_90_alcool_ethylique_agricole_hectolitre:
  description: Carburant constitué d'au minimum 90% d'alcool éthylique agricole (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: null
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: null
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: null
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: null
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: null
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: null
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: null
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: null
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: null
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: null
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: null
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: null
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: null
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: null
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: null
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 4.4
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 6.43
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 7.93
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 9.43
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 10.93
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 12.43
description: TICPE - produits énergétiques e
emulsion_eau_dans_gazole_autres_hectolitre:
  description: Emulsion d'eau dans du gazole …, autres (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: 198.95
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: 24.54
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: 24.54
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: 24.54
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: 24.54
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 30.2
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 30.2
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 26.27
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 24.78
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 28.71
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 28.71
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 28.71
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 28.71
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 30.35
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 32.0
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 33.86
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 36.94
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 39.22
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 41.5
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 43.77
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 46.05
emulsion_eau_dans_gazole_sous_conditions_hectolitre:
  description: Emulsion d'eau dans du gazole …, sous conditions (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: 40.85
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: 1.8
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: 1.8
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: 1.8
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: 1.8
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 2.1
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 2.1
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 2.1
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 2.1
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 2.1
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 2.1
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 2.1
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 2.1
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 3.74
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 5.39
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 7.25
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 10.33
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 12.61
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 14.89
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 17.16
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 19.44
metadata:
  rank: 4
super_e_85_utilise_comme_carburant_hectolitre:
  description: Super E 85 utilisé comme carburant (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      metadata:
        reference: Loi  92-1376 du 30/12/1992 (LF pour 1993)
      value: null
    '1994-01-01':
      metadata:
        reference: Loi  93-1352 du 30/12/1993 (LF pour 1994)
      value: null
    '1995-01-01':
      metadata:
        reference: Loi  94-1162 du 29/12/1994 (LF pour 1995)
      value: null
    '1996-01-01':
      metadata:
        reference: Loi  95-1346 du 30/12/1995 (LF pour 1996)
      value: null
    '1997-01-01':
      metadata:
        reference: Loi  96-1181 du 30/12/1996 (LF pour 1997)
      value: null
    '1998-01-01':
      metadata:
        reference: Loi  97-1269 du 30/12/1997 (LF pour 1998)
      value: null
    '1999-01-01':
      metadata:
        reference: Loi  98-1266 du 30/12/1998 (LF pour 1999)
      value: null
    '2000-01-01':
      metadata:
        reference: Loi  99-1172 du 30/12/1999 (LF pour 2000)
      value: null
    '2002-01-01':
      metadata:
        reference: Loi  2001-1275 du 28/12/2001 (LF pour 2002)
      value: null
    '2003-01-01':
      metadata:
        reference: Loi  2002-1575 du 30/12/2002 (LF pour 2003)
      value: null
    '2004-01-01':
      metadata:
        reference: Loi  2003-1311 du 30/12/2003 (LF pour 2004)
      value: null
    '2006-01-01':
      metadata:
        reference: Loi  2004-1484 du 30/12/2004 (LF pour 2005)
      value: null
    '2008-01-01':
      metadata:
        reference: Loi  2007-1822 du 24/12/2007 (LF pour 2008)
      value: 28.33
    '2008-12-29':
      metadata:
        reference: Loi  2008-1425 du 27/12/2008 (LF pour 2009)  - art. 16 et 17
      value: 28.33
    '2009-01-01':
      metadata:
        reference: Loi  2008-1443 du 30/12/2008 (LFR pour 2008)
      value: 23.24
    '2010-01-01':
      metadata:
        reference: Loi  2009-1674 du 30/12/2009 (LFR pour 2009) - art. 76
      value: 20.69
    '2010-03-11':
      metadata:
        reference: Loi  2010-237 du 09/03/2010 (LFR pour 2010) - art. 4 et 5
      value: 20.69
    '2011-01-01':
      metadata:
        reference: Loi  2010-1657 du 29/12/2010 (LF pour 2011) - art. 138
      value: 17.29
    '2012-01-01':
      metadata:
        reference: Loi  2011-1977 du 28/12/2011 (LF pour 2012) - art. 21
      value: 17.29
    '2014-04-01':
      metadata:
        reference: Loi  2013-1278 du 29/12/2013 (LF pour 2014) - art. 32
      value: 12.4
    '2015-01-01':
      metadata:
        reference: Loi 2014-1654 du 29/12/2014 (LF pour 2015) - art. 36
      value: 12.62
    '2016-01-01':
      metadata:
        reference: Loi 2015-1786 du 29/12/2015 (LFR pour 2015) - art. 14 et 17
      value: 7.96
    '2017-01-01':
      metadata:
        reference: Loi 2016-1918 du 29/12/2016 (LFR pour 2016)
      value: 9.41
    '2018-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 11.83
    '2019-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 13.61
    '2020-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 15.39
    '2021-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 17.17
    '2022-01-01':
      metadata:
        reference: Loi 2017-1837 du 30/12/2017 (LF pour 2018)
      value: 18.95
