butanes_liquefies_autres_100kg_nets:
  description: Butanes liquéfiés, autres (100kg nets)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 65.71
    '2002-01-01':
      value: 10.02
    '2003-01-01':
      value: 10.76
    '2015-01-01':
      value: 13.0
    '2016-01-01':
      value: 13.97
    '2017-01-01':
      value: 16.5
    '2018-01-01':
      value: 20.71
    '2019-01-01':
      value: 23.82
    '2020-01-01':
      value: 26.92
    '2021-01-01':
      value: 30.03
    '2022-01-01':
      value: 33.13
butanes_liquefies_sous_condition_100kg_nets:
  description: Butanes liquéfiés, sous condition (100kg nets)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 25.86
    '2002-01-01':
      value: 3.94
    '2003-01-01':
      value: 4.68
    '2015-01-01':
      value: 6.92
    '2016-01-01':
      value: 9.16
    '2017-01-01':
      value: 11.69
    '2018-01-01':
      value: 15.9
    '2019-01-01':
      value: 19.01
    '2020-01-01':
      value: 22.11
    '2021-01-01':
      value: 25.22
    '2022-01-01':
      value: 28.32
butanes_liquefies_usages_autres_que_comme_carburant_100kg_nets:
  description: Butanes liquéfiés, usages autres que comme carburant (100kg nets)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2018-01-01':
      value: 6.63
    '2019-01-01':
      value: 13.25
    '2020-01-01':
      value: 19.9
    '2021-01-01':
      value: 26.5
    '2022-01-01':
      value: 33.13
description: TICPE - produits énergétiques c
fioul_avec_point_eclair_inferieur_120deg_c_hectolitre:
  description: Fioul avec point d'éclair inférieur à 120° C (hectolitre)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 255.18
    '2002-01-01':
      value: 38.9
    '2003-01-01':
      value: null
fioul_lourd_100kg_net:
  description: Fioul lourd (100kg net)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2003-01-01':
      value: 1.85
    '2014-04-01':
      value: 2.19
    '2015-01-01':
      value: 4.53
    '2016-01-01':
      value: 6.88
    '2017-01-01':
      value: 9.54
    '2018-01-01':
      value: 13.95
    '2019-01-01':
      value: 17.2
    '2020-01-01':
      value: 20.45
    '2021-01-01':
      value: 23.7
    '2022-01-01':
      value: 26.95
fioul_lourd_bts_100kg:
  description: Fioul lourd BTS (100kg)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 9.33
    '1994-01-01':
      value: 10.13
    '1995-01-01':
      value: 10.3
    '1996-01-01':
      value: 10.5
    '1997-01-01':
      value: 10.72
    '1998-01-01':
      value: 10.86
    '1999-01-01':
      value: 10.96
    '2000-01-01':
      value: 11.01
    '2002-01-01':
      value: 1.68
    '2003-01-01':
      value: null
fioul_lourd_hts_100kg:
  description: Fioul lourd HTS (100kg)
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 12.9
    '1994-01-01':
      value: 14.01
    '1995-01-01':
      value: 14.25
    '1996-01-01':
      value: 14.52
    '1997-01-01':
      value: 14.82
    '1998-01-01':
      value: 15.01
    '1999-01-01':
      value: 15.15
    '2000-01-01':
      value: 15.23
    '2002-01-01':
      value: 2.32
    '2003-01-01':
      value: null
gazol_b_10_hectolitre:
  description: Gazol B 10 (hectolitre)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2017-01-01':
      value: 53.07
    '2018-01-01':
      value: 59.4
    '2019-01-01':
      value: 64.76
    '2020-01-01':
      value: 70.12
    '2021-01-01':
      value: 75.47
    '2022-01-01':
      value: 78.23
gazole_autres_hectolitre:
  description: Gazole, autres (hectolitre) *
  metadata:
    unit:
      '1993-04-15': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '1993-04-15':
      value: 174.06
    '1994-01-01':
      value: 210.22
    '1995-01-01':
      value: 213.79
    '1996-01-01':
      value: 226.79
    '1997-01-01':
      value: 232.79
    '1998-01-01':
      value: 240.79
    '1999-01-01':
      value: 248.18
    '2000-01-01':
      value: 255.18
    '2002-01-01':
      value: 38.9
    '2003-01-01':
      value: 39.19
    '2004-01-01':
      value: 41.69
    '2006-01-01':
      value: 42.84
    '2015-01-01':
      value: 46.82
    '2016-01-01':
      value: 49.81
    '2017-01-01':
      value: 53.07
    '2018-01-01':
      value: 59.4
    '2019-01-01':
      value: 64.76
    '2020-01-01':
      value: 70.12
    '2021-01-01':
      value: 75.47
    '2022-01-01':
      value: 78.23
metadata:
  order:
  - gazole_autres_hectolitre
  - gazol_b_10_hectolitre
  - fioul_lourd_100kg_net
  - fioul_avec_point_eclair_inferieur_120deg_c_hectolitre
  - fioul_lourd_hts_100kg
  - fioul_lourd_bts_100kg
  - propane_utilise_comme_carburants_sous_conditions_100kg_nets
  - propane_utilise_comme_carburants_autres_100kg_nets
  - propane_utilise_comme_carburants_usages_autres_que_comme_carburant_100kg_nets
  - butanes_liquefies_sous_condition_100kg_nets
  - butanes_liquefies_autres_100kg_nets
  - butanes_liquefies_usages_autres_que_comme_carburant_100kg_nets
propane_utilise_comme_carburants_autres_100kg_nets:
  description: Propane utilisé comme carburants, autres (100kg nets)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 65.71
    '2002-01-01':
      value: 10.02
    '2003-01-01':
      value: 10.76
    '2015-01-01':
      value: 13.0
    '2016-01-01':
      value: 13.97
    '2017-01-01':
      value: 16.5
    '2018-01-01':
      value: 20.71
    '2019-01-01':
      value: 23.82
    '2020-01-01':
      value: 26.92
    '2021-01-01':
      value: 30.03
    '2022-01-01':
      value: 33.13
propane_utilise_comme_carburants_sous_conditions_100kg_nets:
  description: Propane utilisé comme carburants, sous conditions (100kg nets)
  metadata:
    unit:
      '2000-01-01': currency-FRF
      '2002-01-01': currency-EUR
  values:
    '1993-01-01':
      value: null
    '2000-01-01':
      value: 25.86
    '2002-01-01':
      value: 3.94
    '2003-01-01':
      value: 4.68
    '2015-01-01':
      value: 6.92
    '2016-01-01':
      value: 9.16
    '2017-01-01':
      value: 11.69
    '2018-01-01':
      value: 15.9
    '2019-01-01':
      value: 19.01
    '2020-01-01':
      value: 22.11
    '2021-01-01':
      value: 25.22
    '2022-01-01':
      value: 28.32
propane_utilise_comme_carburants_usages_autres_que_comme_carburant_100kg_nets:
  description: Propane utilisé comme carburants, usages autres que comme carburant
    (100kg nets)
  metadata:
    unit: currency-EUR
  values:
    '1993-01-01':
      value: null
    '2018-01-01':
      value: 6.63
    '2019-01-01':
      value: 13.25
    '2020-01-01':
      value: 19.9
    '2021-01-01':
      value: 26.5
    '2022-01-01':
      value: 33.13
